version: '2'
services:
  db:
    image: mariadb:10.5
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - ./data/mysql:/var/lib/mysql

  bookstack:
    image: styliteag/bookstack:latest
    depends_on:
    - db
    environment:
    - DB_HOST=db:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - ./data/uploads:/var/www/bookstack/public/uploads
    - ./data/storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"
